[package]
name = "explorer_ethereum_crate"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "explorer_ethereum_crate"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
rustler = "0.29.1"
web3 = "0.19.0"
